Repository jenkinsci/oic-auth-plugin, pull requests merged in 2022-10, with the labels that each got.

#90 JENKINS-61609: Add a fallback parse attempt for groups
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: enhancement

#121 #144 add option to use basic token auth method
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/config.jelly
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-tokenAuthMethod.html
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponseTest.java
  src/test/resources/org/jenkinsci/plugins/oic/ConfigurationAsCode.yml
  src/test/resources/org/jenkinsci/plugins/oic/ConfigurationAsCodeExport.yml
Labels: enhancement

#115 Properly restore GrantedAuthorities
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
Labels: bug

#150 Documentation improvement
  CHANGELOG.md
  README.md
  docs/CONTRIBUTING.md
Labels: documentation

#154 Encode post-logout URL of logout redirect
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
Labels: bug

#155 Add unit test of logout URL generation
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
Labels: skip-changelog

#156 Add crowdin links
  README.md
Labels: skip-changelog

#161 Ised canada code
  .gitignore
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java
  src/main/resources/org/jenkinsci/plugins/oic/Messages.properties
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/DescriptorImplTest.java
  src/test/java/org/jenkinsci/plugins/oic/EscapeHatchCrumbExclusionTest.java
  src/test/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactoryTest.java
  src/test/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactoryTest2.java
  src/test/java/org/jenkinsci/plugins/oic/OicLogoutActionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSessionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicUserDetailsTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicUserPropertyTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/java/org/jenkinsci/plugins/oic/TokenResponseTest.java
  src/test/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponseTest.java
Labels: tests

#166 Add checkstyle check
  .mvn/checkstyle-suppressions.xml
  .mvn/checkstyle.xml
  pom.xml
  src/main/java/com/google/api/client/auth/oauth2/TokenResponse.java
  src/main/java/org/jenkinsci/plugins/oic/EscapeHatchCrumbExclusion.java
  src/main/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactory.java
  src/main/java/org/jenkinsci/plugins/oic/OicLogoutAction.java
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/main/java/org/jenkinsci/plugins/oic/OicUserDetails.java
  src/main/java/org/jenkinsci/plugins/oic/OicUserProperty.java
  src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/DescriptorImplTest.java
  src/test/java/org/jenkinsci/plugins/oic/EscapeHatchCrumbExclusionTest.java
  src/test/java/org/jenkinsci/plugins/oic/FieldTest.java
  src/test/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactoryTest.java
  src/test/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactoryTest2.java
  src/test/java/org/jenkinsci/plugins/oic/OicLogoutActionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSessionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicUserDetailsTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicUserPropertyTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/java/org/jenkinsci/plugins/oic/TokenResponseTest.java
  src/test/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponseTest.java
Labels: skip-changelog
