Repository jenkinsci/oic-auth-plugin, pull requests merged in 2024-07, with the labels that each got.

#346 Bump Jenkins version to 2.426.3
  pom.xml
  src/test/java/org/jenkinsci/plugins/oic/EscapeHatchCrumbExclusionTest.java
  src/test/java/org/jenkinsci/plugins/oic/MockHttpServletRequest.java
Labels: dependencies

#350 Remove getter test failing on my locale
  src/test/java/org/jenkinsci/plugins/oic/OicLogoutActionTest.java
Labels: skip-changelog

#310 Implement Token Expiry Check and Refresh using Refresh Tokens
  src/main/java/org/jenkinsci/plugins/oic/OicCredentials.java
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/config.jelly
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/config.properties
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-allowedTokenExpirationClockSkewSeconds.html
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-logoutFromOpenidProvider.html
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-tokenExpirationCheckDisabled.html
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-useRefreshTokens.html
  src/test/java/org/jenkinsci/plugins/oic/OicSessionTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponseTest.java
  src/test/resources/org/jenkinsci/plugins/oic/ConfigurationAsCodeExport.yml
Labels: enhancement

#353 Stop persisting OicSession in HTTP session when only OIDC state is required
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: bug
