Repository jenkinsci/oic-auth-plugin, pull requests merged in 2024-06, with the labels that each got.

#333 Replace `OicUserProperty` with `LastGrantedAuthoritiesProperty`
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicUserProperty.java
  src/test/java/org/jenkinsci/plugins/oic/OicUserPropertyTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: bug

#345 Refactor `PluginTest` to eliminate duplication
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: tests, chore

#344 Set up an error page when the token could not be validated.
  src/main/java/org/jenkinsci/plugins/oic/FailedCheckOfTokenException.java
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/resources/org/jenkinsci/plugins/oic/FailedCheckOfTokenException/error.jelly
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: enhancement
