Repository jenkinsci/oic-auth-plugin, pull requests merged in 2024-10, with the labels that each got.

#417 Update CasC documentation
  docs/configuration/README.md
Labels: documentation

#395 Redirect to login page in case token is expired instead of showing an error page
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: bug

#409 Replace EOL Google Oauth library
  pom.xml
  src/main/java/org/jenkinsci/plugins/oic/AnythingGoesTokenValidator.java
  src/main/java/org/jenkinsci/plugins/oic/CustomOidcConfiguration.java
  src/main/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactory.java
  src/main/java/org/jenkinsci/plugins/oic/OicCrumbExclusion.java
  src/main/java/org/jenkinsci/plugins/oic/OicJsonWebTokenVerifier.java
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicServerConfiguration.java
  src/main/java/org/jenkinsci/plugins/oic/OicServerManualConfiguration.java
  src/main/java/org/jenkinsci/plugins/oic/OicServerWellKnownConfiguration.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/main/java/org/jenkinsci/plugins/oic/OicTokenResponse.java
  src/main/java/org/jenkinsci/plugins/oic/ProxyAwareResourceRetriever.java
  src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java
  src/main/java/org/jenkinsci/plugins/oic/ssl/AnythingGoesTrustManager.java
  src/main/java/org/jenkinsci/plugins/oic/ssl/IgnoringHostNameVerifier.java
  src/main/java/org/jenkinsci/plugins/oic/ssl/TLSUtils.java
  src/main/resources/org/jenkinsci/plugins/oic/Messages.properties
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-sendScopesInTokenRequest.html
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-sendScopesInTokenRequest_fr.html
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-subjectType.html
  src/main/resources/org/jenkinsci/plugins/oic/OicServerManualConfiguration/config.jelly
  src/main/resources/org/jenkinsci/plugins/oic/OicServerManualConfiguration/help-issuer.html
  src/main/resources/org/jenkinsci/plugins/oic/OicServerManualConfiguration/help-issuer_fr.html
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/FieldTest.java
  src/test/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactoryTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicJsonWebTokenVerifierTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicServerWellKnownConfigurationTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSessionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicTokenResponseTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/ProxyAwareResourceRetrieverTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponseTest.java
  src/test/resources/org/jenkinsci/plugins/oic/ConfigurationAsCode.yml
  src/test/resources/org/jenkinsci/plugins/oic/ConfigurationAsCodeExport.yml
  src/test/resources/org/jenkinsci/plugins/oic/ConfigurationAsCodeMinimal.yml
Labels: breaking

#423 [JENKINS-73849] [JEP-237] remove the ability to disable SSL and token validation in FIPS mode
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/resources/org/jenkinsci/plugins/oic/Messages.properties
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmFipsTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/resources/org/jenkinsci/plugins/oic/OicSecurityRealmFipsTest/failsOnMigrationTest/config.xml
  src/test/resources/org/jenkinsci/plugins/oic/OicSecurityRealmFipsTest/worksOnMigrationWithValidValuesTest/config.xml
Labels: chore

#426 Resuse the original user principal to avoid crumb issues.
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
Labels: bug

#440 Use a FIPS compliant version of nimbus-jose-jwt
  pom.xml
Labels: enhancement

#442 Remove unused `<st:once>` tag
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/config.jelly
Labels: skip-changelog
