Repository jenkinsci/oic-auth-plugin, pull requests merged in 2024-04, with the labels that each got.

#286 Fix invalid redirect computation (fix #285)
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
Labels: bug

#288 Compatibility with Jenkins clustered setup
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/test/java/org/jenkinsci/plugins/oic/OicSessionTest.java
Labels: enhancement

#287 Hash escape hatch password in configuration - fix CVE-2023-50770
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/config.jelly
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/resources/org/jenkinsci/plugins/oic/ConfigurationAsCode.yml
Labels: bug

#289 Improve code cleaning
  .git-blame-ignore-revs
  .github/dependabot.yml
  pom.xml
  src/main/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactory.java
  src/main/java/org/jenkinsci/plugins/oic/OicLogoutAction.java
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/main/java/org/jenkinsci/plugins/oic/OicTokenResponse.java
  src/main/java/org/jenkinsci/plugins/oic/OicUserProperty.java
  src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/DescriptorImplTest.java
  src/test/java/org/jenkinsci/plugins/oic/FieldTest.java
  src/test/java/org/jenkinsci/plugins/oic/JenkinsAwareConnectionFactoryTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicLogoutActionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSessionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicTokenResponseTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicUserPropertyTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponseTest.java
Labels: dependencies, skip-changelog

#291 Reimplement PKCE to serialize verifier in session
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: bug

#293 Bump mailer from 1.34.2 to 448.v5b_97805e3767
  pom.xml
Labels: dependencies

#292 Gracefully handle missing and invalid idtoken
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicTokenResponse.java
  src/main/resources/org/jenkinsci/plugins/oic/Messages.properties
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: enhancement

#298 Add open rewrite to pom.xml
  pom.xml
Labels: chore
