Repository jenkinsci/oic-auth-plugin, pull requests merged in 2024-08, with the labels that each got.

#363 Update Jenkins Security Scan action
  .github/workflows/jenkins-security-scan.yml
Labels: skip-changelog, chore

#373 Make hashcode test really useful
  src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java
  src/test/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponseTest.java
Labels: tests

#359 Fix calculation of expiration timestamp
  src/main/java/org/jenkinsci/plugins/oic/OicCredentials.java
Labels: bug
