Repository jenkinsci/oic-auth-plugin, pull requests merged in 2024-05, with the labels that each got.

#303 Ensure login doesn't redirect to logout URL
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
Labels: enhancement

#309 Add HOWTO on groups configuration
  README.md
  docs/FAQ.md
  docs/howto/GROUPS_FROM_IDP.md
  docs/howto/README.md
Labels: chore

#311 Re-activate spotless
  pom.xml
  src/main/java/org/jenkinsci/plugins/oic/OicJsonWebTokenVerifier.java
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/oic/OicSession.java
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicJsonWebTokenVerifierTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: skip-changelog
