Repository jenkinsci/oic-auth-plugin, pull requests merged in 2024-09, with the labels that each got.

#388 Update SCM URL
  pom.xml
Labels: skip-changelog

#389 Forward compatibility with jenkinsci/jenkins#7268
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: developer

#390 POM cleanup
  pom.xml
Labels: developer

#386 Allow access using a Jenkins API token without an OIDC Session
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/config.jelly
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/config.properties
  src/main/resources/org/jenkinsci/plugins/oic/OicSecurityRealm/help-allowTokenAccessWithoutOicSession.html
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: enhancement

#401 Remove deprecated constructor
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/test/java/org/jenkinsci/plugins/oic/DescriptorImplTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
Labels: chore

#402 Use endSessionUrl instead of endSessionEndpoint for manual configuration in UI
  src/main/resources/org/jenkinsci/plugins/oic/OicServerManualConfiguration/config.jelly
Labels: bug
