Repository jenkinsci/oic-auth-plugin, pull requests merged in 2025-02, with the labels that each got.

#507 Fix FormValidation check when overwriting scopes when using the OicServerWellKnownConfiguration
  src/main/java/org/jenkinsci/plugins/oic/OicServerWellKnownConfiguration.java
  src/test/java/org/jenkinsci/plugins/oic/OicServerWellKnownConfigurationTest.java
Labels: skip-changelog, developer

#479 Documented way to look into inward tokens and results of lookup in userInfo endpoint
  docs/howto/DEBUG_IDP.md
  docs/howto/README.md
Labels: documentation

#528 Migrate tests to JUnit5
  pom.xml
  src/test/java/org/jenkinsci/plugins/oic/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/oic/DescriptorImplTest.java
  src/test/java/org/jenkinsci/plugins/oic/EscapeHatchCrumbExclusionTest.java
  src/test/java/org/jenkinsci/plugins/oic/FieldTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicAlgorithmValidatorFIPS140Test.java
  src/test/java/org/jenkinsci/plugins/oic/OicCrumbExclusionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicLogoutActionTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmFIPSAlgoTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmFipsTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmIdStrategyTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicSecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicServerManualConfigurationTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicServerWellKnownConfigurationTest.java
  src/test/java/org/jenkinsci/plugins/oic/OicUserDetailsTest.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
  src/test/java/org/jenkinsci/plugins/oic/ProxyAwareResourceRetrieverTest.java
  src/test/java/org/jenkinsci/plugins/oic/SecurityRealmConfigurationFIPSTest.java
  src/test/java/org/jenkinsci/plugins/oic/TestRealm.java
  src/test/java/org/jenkinsci/plugins/oic/monitor/OicStrategyMonitorTest.java
  src/test/resources/org/jenkinsci/plugins/oic/OicSecurityRealmFipsTest/failsOnMigrationTest/config.xml
Labels: tests, chore

#523 Add support for avatars
  src/main/java/org/jenkinsci/plugins/oic/OicAvatarProperty.java
  src/main/java/org/jenkinsci/plugins/oic/OicAvatarResolver.java
  src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java
  src/test/java/org/jenkinsci/plugins/oic/PluginTest.java
Labels: enhancement

#541 Use JSON Path library plugin
  pom.xml
Labels: internal
